/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "rx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CmdVel, CmdVel, AUTO)


PB_BIND(HardwareCmd, HardwareCmd, AUTO)


PB_BIND(syncMsgRx, syncMsgRx, AUTO)


PB_BIND(RxMsg, RxMsg, AUTO)



