/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_RX_PB_H_INCLUDED
#define PB_RX_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _CmdVel {
    bool has_linear_x;
    float linear_x;
    bool has_angular_z;
    float angular_z;
} CmdVel;

typedef struct _HardwareCmd {
    bool has_vacuum_state;
    uint32_t vacuum_state;
    bool has_side_brushcmd;
    uint32_t side_brushcmd;
} HardwareCmd;

typedef struct _syncMsgRx {
    bool has_pi_initial_time_stamp_us;
    uint32_t pi_initial_time_stamp_us;
    bool has_stm32_rx_time_stamp_us;
    uint32_t stm32_rx_time_stamp_us;
    bool has_stm32_tx_time_stamp_us;
    uint32_t stm32_tx_time_stamp_us;
} syncMsgRx;

typedef struct _RxMsg {
    bool has_cmd_vel;
    CmdVel cmd_vel;
    bool has_hardware_cmd;
    HardwareCmd hardware_cmd;
    bool has_sync_msg_rx;
    syncMsgRx sync_msg_rx;
} RxMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CmdVel_init_default                      {false, 0, false, 0}
#define HardwareCmd_init_default                 {false, 0, false, 0}
#define syncMsgRx_init_default                   {false, 0, false, 0, false, 0}
#define RxMsg_init_default                       {false, CmdVel_init_default, false, HardwareCmd_init_default, false, syncMsgRx_init_default}
#define CmdVel_init_zero                         {false, 0, false, 0}
#define HardwareCmd_init_zero                    {false, 0, false, 0}
#define syncMsgRx_init_zero                      {false, 0, false, 0, false, 0}
#define RxMsg_init_zero                          {false, CmdVel_init_zero, false, HardwareCmd_init_zero, false, syncMsgRx_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define CmdVel_linear_x_tag                      1
#define CmdVel_angular_z_tag                     2
#define HardwareCmd_vacuum_state_tag             2
#define HardwareCmd_side_brushcmd_tag            3
#define syncMsgRx_pi_initial_time_stamp_us_tag   1
#define syncMsgRx_stm32_rx_time_stamp_us_tag     2
#define syncMsgRx_stm32_tx_time_stamp_us_tag     3
#define RxMsg_cmd_vel_tag                        1
#define RxMsg_hardware_cmd_tag                   2
#define RxMsg_sync_msg_rx_tag                    3

/* Struct field encoding specification for nanopb */
#define CmdVel_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    linear_x,          1) \
X(a, STATIC,   OPTIONAL, FLOAT,    angular_z,         2)
#define CmdVel_CALLBACK NULL
#define CmdVel_DEFAULT NULL

#define HardwareCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   vacuum_state,      2) \
X(a, STATIC,   OPTIONAL, UINT32,   side_brushcmd,     3)
#define HardwareCmd_CALLBACK NULL
#define HardwareCmd_DEFAULT NULL

#define syncMsgRx_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   pi_initial_time_stamp_us,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   stm32_rx_time_stamp_us,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   stm32_tx_time_stamp_us,   3)
#define syncMsgRx_CALLBACK NULL
#define syncMsgRx_DEFAULT NULL

#define RxMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cmd_vel,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  hardware_cmd,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sync_msg_rx,       3)
#define RxMsg_CALLBACK NULL
#define RxMsg_DEFAULT NULL
#define RxMsg_cmd_vel_MSGTYPE CmdVel
#define RxMsg_hardware_cmd_MSGTYPE HardwareCmd
#define RxMsg_sync_msg_rx_MSGTYPE syncMsgRx

extern const pb_msgdesc_t CmdVel_msg;
extern const pb_msgdesc_t HardwareCmd_msg;
extern const pb_msgdesc_t syncMsgRx_msg;
extern const pb_msgdesc_t RxMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CmdVel_fields &CmdVel_msg
#define HardwareCmd_fields &HardwareCmd_msg
#define syncMsgRx_fields &syncMsgRx_msg
#define RxMsg_fields &RxMsg_msg

/* Maximum encoded size of messages (where known) */
#define CmdVel_size                              10
#define HardwareCmd_size                         12
#define RX_PB_H_MAX_SIZE                         RxMsg_size
#define RxMsg_size                               46
#define syncMsgRx_size                           18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
