/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_RX_PB_H_INCLUDED
#define PB_RX_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _CmdVel {
    bool has_linearX;
    float linearX;
    bool has_AngleZ;
    float AngleZ;
} CmdVel;

typedef struct _HardwareCmd {
    bool has_vacuumState;
    uint32_t vacuumState;
    bool has_SideBrushCmd;
    uint32_t SideBrushCmd;
} HardwareCmd;

typedef struct _syncMsgRx {
    bool has_piIintialTimeStamp_us;
    uint32_t piIintialTimeStamp_us;
    bool has_stm32RxTimeStamp_us;
    uint32_t stm32RxTimeStamp_us;
    bool has_stm32TxTimeStamp_us;
    uint32_t stm32TxTimeStamp_us;
} syncMsgRx;

typedef struct _RxMsg {
    bool has_cmdVel;
    CmdVel cmdVel;
    bool has_hardwareCmd;
    HardwareCmd hardwareCmd;
    bool has_syncMsgRx;
    syncMsgRx syncMsgRx;
} RxMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CmdVel_init_default                      {false, 0, false, 0}
#define HardwareCmd_init_default                 {false, 0, false, 0}
#define syncMsgRx_init_default                   {false, 0, false, 0, false, 0}
#define RxMsg_init_default                       {false, CmdVel_init_default, false, HardwareCmd_init_default, false, syncMsgRx_init_default}
#define CmdVel_init_zero                         {false, 0, false, 0}
#define HardwareCmd_init_zero                    {false, 0, false, 0}
#define syncMsgRx_init_zero                      {false, 0, false, 0, false, 0}
#define RxMsg_init_zero                          {false, CmdVel_init_zero, false, HardwareCmd_init_zero, false, syncMsgRx_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define CmdVel_linearX_tag                       1
#define CmdVel_AngleZ_tag                        2
#define HardwareCmd_vacuumState_tag              2
#define HardwareCmd_SideBrushCmd_tag             3
#define syncMsgRx_piIintialTimeStamp_us_tag      1
#define syncMsgRx_stm32RxTimeStamp_us_tag        2
#define syncMsgRx_stm32TxTimeStamp_us_tag        3
#define RxMsg_cmdVel_tag                         1
#define RxMsg_hardwareCmd_tag                    2
#define RxMsg_syncMsgRx_tag                      3

/* Struct field encoding specification for nanopb */
#define CmdVel_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    linearX,           1) \
X(a, STATIC,   OPTIONAL, FLOAT,    AngleZ,            2)
#define CmdVel_CALLBACK NULL
#define CmdVel_DEFAULT NULL

#define HardwareCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   vacuumState,       2) \
X(a, STATIC,   OPTIONAL, UINT32,   SideBrushCmd,      3)
#define HardwareCmd_CALLBACK NULL
#define HardwareCmd_DEFAULT NULL

#define syncMsgRx_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   piIintialTimeStamp_us,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   stm32RxTimeStamp_us,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   stm32TxTimeStamp_us,   3)
#define syncMsgRx_CALLBACK NULL
#define syncMsgRx_DEFAULT NULL

#define RxMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cmdVel,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  hardwareCmd,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  syncMsgRx,         3)
#define RxMsg_CALLBACK NULL
#define RxMsg_DEFAULT NULL
#define RxMsg_cmdVel_MSGTYPE CmdVel
#define RxMsg_hardwareCmd_MSGTYPE HardwareCmd
#define RxMsg_syncMsgRx_MSGTYPE syncMsgRx

extern const pb_msgdesc_t CmdVel_msg;
extern const pb_msgdesc_t HardwareCmd_msg;
extern const pb_msgdesc_t syncMsgRx_msg;
extern const pb_msgdesc_t RxMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CmdVel_fields &CmdVel_msg
#define HardwareCmd_fields &HardwareCmd_msg
#define syncMsgRx_fields &syncMsgRx_msg
#define RxMsg_fields &RxMsg_msg

/* Maximum encoded size of messages (where known) */
#define CmdVel_size                              10
#define HardwareCmd_size                         12
#define RX_PB_H_MAX_SIZE                         RxMsg_size
#define RxMsg_size                               46
#define syncMsgRx_size                           18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
