# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rx.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08rx.proto\"J\n\x06\x43mdVel\x12\x14\n\x07linearX\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x13\n\x06\x41ngleZ\x18\x02 \x01(\x02H\x01\x88\x01\x01\x42\n\n\x08_linearXB\t\n\x07_AngleZ\"c\n\x0bHardwareCmd\x12\x18\n\x0bvacuumState\x18\x02 \x01(\rH\x00\x88\x01\x01\x12\x19\n\x0cSideBrushCmd\x18\x03 \x01(\rH\x01\x88\x01\x01\x42\x0e\n\x0c_vacuumStateB\x0f\n\r_SideBrushCmd\"\xbd\x01\n\tsyncMsgRx\x12\"\n\x15piIintialTimeStamp_us\x18\x01 \x01(\rH\x00\x88\x01\x01\x12 \n\x13stm32RxTimeStamp_us\x18\x02 \x01(\rH\x01\x88\x01\x01\x12 \n\x13stm32TxTimeStamp_us\x18\x03 \x01(\rH\x02\x88\x01\x01\x42\x18\n\x16_piIintialTimeStamp_usB\x16\n\x14_stm32RxTimeStamp_usB\x16\n\x14_stm32TxTimeStamp_us\"\x9a\x01\n\x05RxMsg\x12\x1c\n\x06\x63mdVel\x18\x01 \x01(\x0b\x32\x07.CmdVelH\x00\x88\x01\x01\x12&\n\x0bhardwareCmd\x18\x02 \x01(\x0b\x32\x0c.HardwareCmdH\x01\x88\x01\x01\x12\"\n\tsyncMsgRx\x18\x03 \x01(\x0b\x32\n.syncMsgRxH\x02\x88\x01\x01\x42\t\n\x07_cmdVelB\x0e\n\x0c_hardwareCmdB\x0c\n\n_syncMsgRxb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CMDVEL']._serialized_start=12
  _globals['_CMDVEL']._serialized_end=86
  _globals['_HARDWARECMD']._serialized_start=88
  _globals['_HARDWARECMD']._serialized_end=187
  _globals['_SYNCMSGRX']._serialized_start=190
  _globals['_SYNCMSGRX']._serialized_end=379
  _globals['_RXMSG']._serialized_start=382
  _globals['_RXMSG']._serialized_end=536
# @@protoc_insertion_point(module_scope)
