/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Odom, Odom, AUTO)


PB_BIND(Imu, Imu, AUTO)


PB_BIND(ToFArray, ToFArray, AUTO)


PB_BIND(Battery, Battery, AUTO)


PB_BIND(syncMsgTx, syncMsgTx, AUTO)


PB_BIND(TxMsg, TxMsg, AUTO)



