/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TX_PB_H_INCLUDED
#define PB_TX_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Odom {
    bool has_x;
    float x;
    bool has_y;
    float y;
    bool has_yaw;
    float yaw;
    bool has_linear_x;
    float linear_x;
    bool has_angular_z;
    float angular_z;
    bool has_odomTimeStamp_us;
    uint32_t odomTimeStamp_us;
} Odom;

typedef struct _Imu {
    bool has_ax;
    float ax;
    bool has_ay;
    float ay;
    bool has_az;
    float az;
    bool has_gx;
    float gx;
    bool has_gy;
    float gy;
    bool has_gz;
    float gz;
    bool has_mpu6500TimeStamp_us;
    uint32_t mpu6500TimeStamp_us;
} Imu;

typedef struct _ToFArray {
    bool has_cliff1;
    uint32_t cliff1;
    bool has_cliff2;
    uint32_t cliff2;
    bool has_cliff3;
    uint32_t cliff3;
    bool has_cliff4;
    uint32_t cliff4;
    bool has_tofTimeStamp_us;
    uint32_t tofTimeStamp_us;
} ToFArray;

typedef struct _Battery {
    bool has_ChargingState;
    uint32_t ChargingState;
    bool has_StateOfCharge;
    float StateOfCharge;
} Battery;

typedef struct _syncMsgTx {
    bool has_piIintialTimeStamp_us;
    uint32_t piIintialTimeStamp_us;
    bool has_stm32RxTimeStamp_us;
    uint32_t stm32RxTimeStamp_us;
    bool has_stm32TxTimeStamp_us;
    uint32_t stm32TxTimeStamp_us;
} syncMsgTx;

typedef struct _TxMsg {
    bool has_odom;
    Odom odom;
    bool has_imu;
    Imu imu;
    bool has_tofArray;
    ToFArray tofArray;
    bool has_battery;
    Battery battery;
    bool has_syncMsgTx;
    syncMsgTx syncMsgTx;
} TxMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Odom_init_default                        {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Imu_init_default                         {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ToFArray_init_default                    {false, 0, false, 0, false, 0, false, 0, false, 0}
#define Battery_init_default                     {false, 0, false, 0}
#define syncMsgTx_init_default                   {false, 0, false, 0, false, 0}
#define TxMsg_init_default                       {false, Odom_init_default, false, Imu_init_default, false, ToFArray_init_default, false, Battery_init_default, false, syncMsgTx_init_default}
#define Odom_init_zero                           {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Imu_init_zero                            {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ToFArray_init_zero                       {false, 0, false, 0, false, 0, false, 0, false, 0}
#define Battery_init_zero                        {false, 0, false, 0}
#define syncMsgTx_init_zero                      {false, 0, false, 0, false, 0}
#define TxMsg_init_zero                          {false, Odom_init_zero, false, Imu_init_zero, false, ToFArray_init_zero, false, Battery_init_zero, false, syncMsgTx_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Odom_x_tag                               1
#define Odom_y_tag                               2
#define Odom_yaw_tag                             3
#define Odom_linear_x_tag                        4
#define Odom_angular_z_tag                       5
#define Odom_odomTimeStamp_us_tag                6
#define Imu_ax_tag                               1
#define Imu_ay_tag                               2
#define Imu_az_tag                               3
#define Imu_gx_tag                               4
#define Imu_gy_tag                               5
#define Imu_gz_tag                               6
#define Imu_mpu6500TimeStamp_us_tag              7
#define ToFArray_cliff1_tag                      1
#define ToFArray_cliff2_tag                      2
#define ToFArray_cliff3_tag                      3
#define ToFArray_cliff4_tag                      4
#define ToFArray_tofTimeStamp_us_tag             5
#define Battery_ChargingState_tag                1
#define Battery_StateOfCharge_tag                2
#define syncMsgTx_piIintialTimeStamp_us_tag      1
#define syncMsgTx_stm32RxTimeStamp_us_tag        2
#define syncMsgTx_stm32TxTimeStamp_us_tag        3
#define TxMsg_odom_tag                           1
#define TxMsg_imu_tag                            2
#define TxMsg_tofArray_tag                       3
#define TxMsg_battery_tag                        4
#define TxMsg_syncMsgTx_tag                      5

/* Struct field encoding specification for nanopb */
#define Odom_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    x,                 1) \
X(a, STATIC,   OPTIONAL, FLOAT,    y,                 2) \
X(a, STATIC,   OPTIONAL, FLOAT,    yaw,               3) \
X(a, STATIC,   OPTIONAL, FLOAT,    linear_x,          4) \
X(a, STATIC,   OPTIONAL, FLOAT,    angular_z,         5) \
X(a, STATIC,   OPTIONAL, UINT32,   odomTimeStamp_us,   6)
#define Odom_CALLBACK NULL
#define Odom_DEFAULT NULL

#define Imu_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    ax,                1) \
X(a, STATIC,   OPTIONAL, FLOAT,    ay,                2) \
X(a, STATIC,   OPTIONAL, FLOAT,    az,                3) \
X(a, STATIC,   OPTIONAL, FLOAT,    gx,                4) \
X(a, STATIC,   OPTIONAL, FLOAT,    gy,                5) \
X(a, STATIC,   OPTIONAL, FLOAT,    gz,                6) \
X(a, STATIC,   OPTIONAL, UINT32,   mpu6500TimeStamp_us,   7)
#define Imu_CALLBACK NULL
#define Imu_DEFAULT NULL

#define ToFArray_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   cliff1,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   cliff2,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   cliff3,            3) \
X(a, STATIC,   OPTIONAL, UINT32,   cliff4,            4) \
X(a, STATIC,   OPTIONAL, UINT32,   tofTimeStamp_us,   5)
#define ToFArray_CALLBACK NULL
#define ToFArray_DEFAULT NULL

#define Battery_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   ChargingState,     1) \
X(a, STATIC,   OPTIONAL, FLOAT,    StateOfCharge,     2)
#define Battery_CALLBACK NULL
#define Battery_DEFAULT NULL

#define syncMsgTx_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   piIintialTimeStamp_us,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   stm32RxTimeStamp_us,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   stm32TxTimeStamp_us,   3)
#define syncMsgTx_CALLBACK NULL
#define syncMsgTx_DEFAULT NULL

#define TxMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  odom,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  imu,               2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tofArray,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  battery,           4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  syncMsgTx,         5)
#define TxMsg_CALLBACK NULL
#define TxMsg_DEFAULT NULL
#define TxMsg_odom_MSGTYPE Odom
#define TxMsg_imu_MSGTYPE Imu
#define TxMsg_tofArray_MSGTYPE ToFArray
#define TxMsg_battery_MSGTYPE Battery
#define TxMsg_syncMsgTx_MSGTYPE syncMsgTx

extern const pb_msgdesc_t Odom_msg;
extern const pb_msgdesc_t Imu_msg;
extern const pb_msgdesc_t ToFArray_msg;
extern const pb_msgdesc_t Battery_msg;
extern const pb_msgdesc_t syncMsgTx_msg;
extern const pb_msgdesc_t TxMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Odom_fields &Odom_msg
#define Imu_fields &Imu_msg
#define ToFArray_fields &ToFArray_msg
#define Battery_fields &Battery_msg
#define syncMsgTx_fields &syncMsgTx_msg
#define TxMsg_fields &TxMsg_msg

/* Maximum encoded size of messages (where known) */
#define Battery_size                             11
#define Imu_size                                 36
#define Odom_size                                31
#define TX_PB_H_MAX_SIZE                         TxMsg_size
#define ToFArray_size                            30
#define TxMsg_size                               136
#define syncMsgTx_size                           18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
